name: hello-quantum
channels:
  - conda-forge
  - defaults
dependencies:
- python=3.11
- notebook
- jupyterlab
- matplotlib
- ipywidgets
- pylatexenc
- pip
- pip:
  - numpy
  - qiskit
  - qiskit-aer
  - celluloid
  - qiskit-ibm-runtime
