name: hello-quantum
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11,<3.12
  - notebook>=7.2.0,<8.0.0
  - jupyterlab>=4.2.0,<5.0.0
  - ipywidgets>=8.1.0,<9.0.0
  - matplotlib>=3.9.0,<4.0.0
  - pylatexenc>=2.10.0,<3.0.0
  - pip>=24.0.0
  - pip:
      - numpy>=2.1.0,<3.0.0
      - qiskit~=1.2.0
      - qiskit-aer~=0.15.0
      - qiskit-ibm-runtime~=0.32.0
      - celluloid>=0.2.0,<0.3.0